services:
  - type: web
    name: cl-vidracaria-sistema
    runtime: php
    plan: free
    region: ohio
    buildCommand: composer install
    envVars:
      - key: PHP_VERSION
        value: 8.2
      - key: DOCUMENT_ROOT
        value: .